In [ ]:
import numpy as np

print(np.__version__)

2.1.3


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print("Arr: ", arr)

print("Type: ", type(arr))

Arr:  [1 2 3 4 5]
Type:  <class 'numpy.ndarray'>


In [ ]:
arr.shape

(5,)

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d)

print("Shape: ", arr2d.shape)

[[1 2 3]
 [4 5 6]]
Shape:  (2, 3)


In [ ]:
arr3d = np.array(
    [
        [
            [1, 2, 3, 4],
            [5, 6, 7, 8]
        ],
        [
            [9, 10, 11, 12],
            [13, 14, 15, 16],
        ],
        [
            [17, 18, 19, 20],
            [21, 22, 23, 24]
        ]
    ]
)

print(arr3d)

print("Shape: ", arr3d.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
Shape:  (3, 2, 4)


In [ ]:
arr_str = np.array(['hello', 'nama', 'saya'])
print(arr_str)

['hello' 'nama' 'saya']


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr[2])

print(arr[0] + arr[4])

3
6


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr[0][2])
print(arr[1][1])

3
5


In [ ]:
arr = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

# menampilkan angka 8
print(arr[1][0][1])

# menampilakn angka 12
print(arr[1][1][2])



8
12


In [ ]:
implementasi_array_3d = np.array([
    [[1, 2], [4, 3], [7, 4]],
    [[2, 0], [9, 0], [7, 5]],
    [[1, 0], [3, 0], [0, 2]],
    [[9, 0], [6, 0], [9, 8]]
])

print(implementasi_array_3d)

print("\nshape", implementasi_array_3d.shape)

[[[1 2]
  [4 3]
  [7 4]]

 [[2 0]
  [9 0]
  [7 5]]

 [[1 0]
  [3 0]
  [0 2]]

 [[9 0]
  [6 0]
  [9 8]]]

shape (4, 3, 2)


In [ ]:
target = implementasi_array_3d[2][1:][0]
print(target)

[3 0]


In [ ]:
arr = np.array(['1', '2', '3', '4', '5'])
print(arr)

arr_int = arr.astype(int)
print("Integer", arr_int)

arr_float = arr.astype(float)
print("Float", arr_float)

['1' '2' '3' '4' '5']
Integer [1 2 3 4 5]
Float [1. 2. 3. 4. 5.]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr)
print('Shape', arr.shape, '\n')

new_arr_2d = arr.reshape(3, 4)

print(new_arr_2d)
print('Shape', new_arr_2d.shape, '\n')

new_arr_3d = arr.reshape(3, 2, 2)

print(new_arr_3d)
print('Shape', new_arr_3d.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape (12,) 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape (3, 4) 

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Shape (3, 2, 2)


In [ ]:
arr = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [13, 14, 15]]
])

print(arr)
print('sesudah di reshape')

new_arr = arr.reshape(-1)

print(new_arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [13 14 15]]]
sesudah di reshape
[ 1  2  3  4  5  6  7  8  9 13 14 15]


In [ ]:
print(len(implementasi_array_3d))
print(implementasi_array_3d.shape)

4
(4, 3, 2)


In [ ]:
for sumbu_0 in implementasi_array_3d:
  for sumbu_1 in sumbu_0:
    for sumbu_2 in sumbu_1:
      print(sumbu_2, end=", ")

1, 2, 4, 3, 7, 4, 2, 0, 9, 0, 7, 5, 1, 0, 3, 0, 0, 2, 9, 0, 6, 0, 9, 8, 

In [ ]:
for idx_sumbu_0 in range(implementasi_array_3d.shape[0]):
  for idx_sumbu_1 in range(implementasi_array_3d.shape[1]):
    for idx_sumbu_2 in range(implementasi_array_3d.shape[2]):
      print(implementasi_array_3d[idx_sumbu_0][idx_sumbu_1][idx_sumbu_2], end=", ")

1, 2, 4, 3, 7, 4, 2, 0, 9, 0, 7, 5, 1, 0, 3, 0, 0, 2, 9, 0, 6, 0, 9, 8, 

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2), axis=0)
print(arr)

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarray = np.array_split(arr, 5)

print('sebelum \n', arr)
print('setelah \n', newarray)

narr = newarray[2]
print(narr)

sebelum 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
setelah 
 [array([1, 2, 3]), array([4, 5, 6]), array([7, 8]), array([ 9, 10]), array([11, 12])]
[7 8]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

x = np.where(arr == 3)

print(x)

(array([2]),)


In [ ]:
arr = np.array([11, 21, 3, 4, 19, 1, 21, 12])
sorted_arr = np.sort(arr)

print(arr)
print(sorted_arr)

[11 21  3  4 19  1 21 12]
[ 1  3  4 11 12 19 21 21]


In [ ]:
from numpy import random

x =  random.rand(2)
print(x)

[0.25528719 0.22647703]


In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

arr3 = np.add(arr1, arr2)
print(arr3)

[11 22 33 44 55]


In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr3 = np.sum(arr1)

print(arr3)

15


In [ ]:
arr1 = np.array([1, 2, 3, 4, 5,])
arr3 = np.prod(arr1)

print(arr3)

120


PANDAS

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = [2, 3, 5, 7, 1]
df = pd.DataFrame(data)
df

,0
0,2
1,3
2,5
3,7
4,1


In [ ]:
data = [['adi', 34], ['Maya', 23], ['Joko', 20]]
df = pd.DataFrame(data, columns=['Nama', 'Usia'], index=['satu', 'dua', 'tiga'])
df

,Nama,Usia
satu,adi,34
dua,Maya,23
tiga,Joko,20


In [ ]:
data = {'nama': ['adi', 'Maya', 'Joko'], 'usia': [34, 23, 20]}
df = pd.DataFrame(data)
df['Alamat'] = ['Jakarta', 'Bandung', 'Surabaya']
df

,nama,usia,Alamat
0,adi,34,Jakarta
1,Maya,23,Bandung
2,Joko,20,Surabaya


In [ ]:
data = {'nama': ['adi', 'Maya', 'Joko'], 'usia': [34, 23, 20]}
df = pd.DataFrame(data)
print(df)
alamat = ['Jakarta', 'Bandung', 'Surabaya']
df.insert(0, 'Alamat', alamat)
print(df)

   nama  usia
0   adi    34
1  Maya    23
2  Joko    20
     Alamat  nama  usia
0   Jakarta   adi    34
1   Bandung  Maya    23
2  Surabaya  Joko    20


In [ ]:
data = [['adi', 34], ['Maya', 23], ['Joko', 20]]
df = pd.DataFrame(data, columns = ['Nama', 'Umur'])
alamat = ['Jakarta', 'Bandung', 'Surabaya']
df.insert(1, 'Alamat', alamat)
print(df)

   Nama    Alamat  Umur
0   adi   Jakarta    34
1  Maya   Bandung    23
2  Joko  Surabaya    20


In [ ]:
data = [['adi', 34], ['Maya', 23], ['Joko', 20]]
df = pd.DataFrame(data, columns = ['Nama', 'Umur'])
print(df)
alamat = ['Jakarta', 'Bandung', 'Surabaya']
pekerjaan = ['Programer', 'DB Admin', 'Web Developer']
df = df.assign(Job = pekerjaan, Alamat = alamat)
print(df)

   Nama  Umur
0   adi    34
1  Maya    23
2  Joko    20
   Nama  Umur            Job    Alamat
0   adi    34      Programer   Jakarta
1  Maya    23       DB Admin   Bandung
2  Joko    20  Web Developer  Surabaya


In [ ]:
data = [['adi', 34], ['Maya', 23], ['Joko', 20]]
df = pd.DataFrame(data, columns = ['Nama', 'Umur'])
print(df)
alamat = ['Jakarta', 'Bandung', 'Surabaya']
pekerjaan = ['Programer', 'DB Admin', 'Web Developer']
d_kolom={'Addess': alamat, 'Job': pekerjaan}
df[['Addess', 'Job']] = pd.DataFrame(d_kolom)
print(df)

   Nama  Umur
0   adi    34
1  Maya    23
2  Joko    20
   Nama  Umur    Addess            Job
0   adi    34   Jakarta      Programer
1  Maya    23   Bandung       DB Admin
2  Joko    20  Surabaya  Web Developer


In [ ]:
data = {
  'nama': ['adi', 'Maya', 'Joko'],
  'usia': [34, 23, 20],
  'alamat': ['Jakarta', 'Bandung', 'Surabaya'],
  'pekerjaan': ['Programer', 'DB Admin', 'Web Developer']
}
df = pd.DataFrame(data)
print(df)
df.drop('pekerjaan', axis=1, inplace=True)
df

   nama  usia    alamat      pekerjaan
0   adi    34   Jakarta      Programer
1  Maya    23   Bandung       DB Admin
2  Joko    20  Surabaya  Web Developer


,nama,usia,alamat
0,adi,34,Jakarta
1,Maya,23,Bandung
2,Joko,20,Surabaya


In [ ]:
data = {
  'nama': ['adi', 'Maya', 'Joko'],
  'usia': [34, 23, 20],
  'alamat': ['Jakarta', 'Bandung', 'Surabaya'],
  'pekerjaan': ['Programer', 'DB Admin', 'Web Developer']
}
df = pd.DataFrame(data)
print(df)
df.pop('pekerjaan')
df

   nama  usia    alamat      pekerjaan
0   adi    34   Jakarta      Programer
1  Maya    23   Bandung       DB Admin
2  Joko    20  Surabaya  Web Developer


,nama,usia,alamat
0,adi,34,Jakarta
1,Maya,23,Bandung
2,Joko,20,Surabaya


In [ ]:
data = {
  'nama': ['adi', 'Maya', 'Joko'],
  'usia': [34, 23, 20],
  'alamat': ['Jakarta', 'Bandung', 'Surabaya'],
  'pekerjaan': ['Programer', 'DB Admin', 'Web Developer']
}
df = pd.DataFrame(data)
print(df)
del df['pekerjaan']
df

   nama  usia    alamat      pekerjaan
0   adi    34   Jakarta      Programer
1  Maya    23   Bandung       DB Admin
2  Joko    20  Surabaya  Web Developer


,nama,usia,alamat
0,adi,34,Jakarta
1,Maya,23,Bandung
2,Joko,20,Surabaya


In [ ]:
data = {
  'nama': ['adi', 'Maya', 'Joko'],
  'usia': [34, 23, 20],
  'alamat': ['Jakarta', 'Bandung', 'Surabaya'],
  'pekerjaan': ['Programer', 'DB Admin', 'Web Developer']
}
df = pd.DataFrame(data)
print(df)
df.drop(['pekerjaan', 'alamat'], axis=1, inplace=True)
df

   nama  usia    alamat      pekerjaan
0   adi    34   Jakarta      Programer
1  Maya    23   Bandung       DB Admin
2  Joko    20  Surabaya  Web Developer


,nama,usia
0,adi,34
1,Maya,23
2,Joko,20


In [ ]:
data = {
  'nama': ['adi', 'Maya', 'Joko', 'Andi'],
  'usia': [34, 23, 20, 23],
  'alamat': ['Jakarta', 'Bandung', 'Surabaya', 'Jakarta'],
  'pekerjaan': ['Programer', 'DB Admin', 'Web Developer', 'Programer']
}
df = pd.DataFrame(data, index=[2, 3, 0, 1])
df

,nama,usia,alamat,pekerjaan
2,adi,34,Jakarta,Programer
3,Maya,23,Bandung,DB Admin
0,Joko,20,Surabaya,Web Developer
1,Andi,23,Jakarta,Programer


In [ ]:
sorted_df = df.sort_index()
sorted_df

,nama,usia,alamat,pekerjaan
0,Joko,20,Surabaya,Web Developer
1,Andi,23,Jakarta,Programer
2,adi,34,Jakarta,Programer
3,Maya,23,Bandung,DB Admin


In [ ]:
sorted_column = sorted_df.sort_index(axis=1)
sorted_column

,alamat,nama,pekerjaan,usia
0,Surabaya,Joko,Web Developer,20
1,Jakarta,Andi,Programer,23
2,Jakarta,adi,Programer,34
3,Bandung,Maya,DB Admin,23


In [ ]:
data = {
  'nama': ['adi', 'Maya', 'Joko', 'Andi'],
  'usia': [34, 23, 20, 23],
  'alamat': ['Jakarta', 'Bandung', 'Surabaya', 'Jakarta'],
  'pekerjaan': ['Programer', 'DB Admin', 'Web Developer', 'Programer']
}
df = pd.DataFrame(data, index=[2, 3, 0, 1])
print(df)
df_sorted = df.sort_values(by='nama')
df_sorted

   nama  usia    alamat      pekerjaan
2   adi    34   Jakarta      Programer
3  Maya    23   Bandung       DB Admin
0  Joko    20  Surabaya  Web Developer
1  Andi    23   Jakarta      Programer


,nama,usia,alamat,pekerjaan
1,Andi,23,Jakarta,Programer
0,Joko,20,Surabaya,Web Developer
3,Maya,23,Bandung,DB Admin
2,adi,34,Jakarta,Programer


In [ ]:
df_sorted = df.sort_values(by=['alamat', 'nama'])
df_sorted

,nama,usia,alamat,pekerjaan
3,Maya,23,Bandung,DB Admin
1,Andi,23,Jakarta,Programer
2,adi,34,Jakarta,Programer
0,Joko,20,Surabaya,Web Developer


In [ ]:
data = {
  'nama': ['adi', 'Maya', 'Joko', 'Andi'],
  'usia': [34, 23, 20, 23],
  'alamat': ['Jakarta', 'Bandung', 'Surabaya', 'Jakarta'],
  'pekerjaan': ['Programer', 'DB Admin', 'Web Developer', 'Programer']
}
df = pd.DataFrame(data)
print(df)
filtered_df = df[df.usia > 30]
filtered_df

   nama  usia    alamat      pekerjaan
0   adi    34   Jakarta      Programer
1  Maya    23   Bandung       DB Admin
2  Joko    20  Surabaya  Web Developer
3  Andi    23   Jakarta      Programer


,nama,usia,alamat,pekerjaan
0,adi,34,Jakarta,Programer


In [ ]:
filtered_df = df[(df.usia > 22) & (df.alamat == 'Jakarta')]
filtered_df

,nama,usia,alamat,pekerjaan
0,adi,34,Jakarta,Programer
3,Andi,23,Jakarta,Programer


In [ ]:
data = {
  'nama': ['adi', 'Maya', 'Joko', 'Andi'],
  'usia': [34, 23, 20, 23],
  'alamat': ['Jakarta', 'Bandung', 'Surabaya', 'Jakarta'],
  'pekerjaan': ['Programer', 'DB Admin', 'Web Developer', 'Programer']
}
df = pd.DataFrame(data)
nama1 = ['Joko', 'Maya']
filtered_df = df[df.nama.isin(nama1)]
filtered_df

,nama,usia,alamat,pekerjaan
1,Maya,23,Bandung,DB Admin
2,Joko,20,Surabaya,Web Developer


In [ ]:
filtered = df.query("nama=='Joko' | nama=='Maya'")
filtered

,nama,usia,alamat,pekerjaan
1,Maya,23,Bandung,DB Admin
2,Joko,20,Surabaya,Web Developer


In [ ]:
df.loc[(df.usia>30)]

,nama,usia,alamat,pekerjaan
0,adi,34,Jakarta,Programer


In [ ]:
df[df.pekerjaan.str.contains('Web')]

,nama,usia,alamat,pekerjaan
2,Joko,20,Surabaya,Web Developer


In [ ]:
data = {
  'nama': ['adi', 'Maya', 'Joko', 'Andi'],
  'usia': [34, 23, 20, 23],
  'alamat': ['Jakarta', 'Bandung', 'Surabaya', 'Jakarta'],
  'pekerjaan': ['Programer', 'DB Admin', 'Web Developer', 'Programer'],
  'gaji': [2000, 3000, 2400, 5000]
}

df = pd.DataFrame(data)
df

,nama,usia,alamat,pekerjaan,gaji
0,adi,34,Jakarta,Programer,2000
1,Maya,23,Bandung,DB Admin,3000
2,Joko,20,Surabaya,Web Developer,2400
3,Andi,23,Jakarta,Programer,5000


In [ ]:
df.groupby('pekerjaan').groups

{'DB Admin': [1], 'Programer': [0, 3], 'Web Developer': [2]}

In [ ]:
df_group = df.groupby('pekerjaan')

for pekerjaan, group in df_group:
  print(pekerjaan)
  print(group)

DB Admin
   nama  usia   alamat pekerjaan  gaji
1  Maya    23  Bandung  DB Admin  3000
Programer
   nama  usia   alamat  pekerjaan  gaji
0   adi    34  Jakarta  Programer  2000
3  Andi    23  Jakarta  Programer  5000
Web Developer
   nama  usia    alamat      pekerjaan  gaji
2  Joko    20  Surabaya  Web Developer  2400


In [ ]:
print(df_group.get_group('DB Admin'))

   nama  usia   alamat pekerjaan  gaji
1  Maya    23  Bandung  DB Admin  3000


In [ ]:
data = {
  'nama': ['adi', 'Maya', 'Joko', 'Andi'],
  'usia': [34, 23, 20, 23],
  'alamat': ['Jakarta', 'Bandung', 'Surabaya', 'Jakarta'],
  'pekerjaan': ['Programer', 'DB Admin', 'Web Developer', 'Programer'],
  'gaji': [2000, 3000, 2400, 5000]
}

df = pd.DataFrame(data)
print('Sebelum di kelompokkan \n', df)

df_group = df.groupby('pekerjaan').mean(numeric_only=True)
print('Setelah di kelompokkan')
df_group

Sebelum di kelompokkan 
    nama  usia    alamat      pekerjaan  gaji
0   adi    34   Jakarta      Programer  2000
1  Maya    23   Bandung       DB Admin  3000
2  Joko    20  Surabaya  Web Developer  2400
3  Andi    23   Jakarta      Programer  5000
Setelah di kelompokkan


,usia,gaji
pekerjaan,,
DB Admin,23.0,3000.0
Programer,28.5,3500.0
Web Developer,20.0,2400.0


In [ ]:
df_group = df.groupby('pekerjaan').mean(numeric_only=True)
df_group

,usia,gaji
pekerjaan,,
DB Admin,23.0,3000.0
Programer,28.5,3500.0
Web Developer,20.0,2400.0


In [ ]:
df_group = df.groupby('pekerjaan').agg({
    'usia': [np.mean, np.sum, np.std],
    'gaji': [np.mean, np.sum, np.std]
})
df_group

/tmp/ipykernel_506/4252965023.py:1: FutureWarning: The provided callable <function mean at 0x788a8fd6fe20> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df_group = df.groupby('pekerjaan').agg({
/tmp/ipykernel_506/4252965023.py:1: FutureWarning: The provided callable <function sum at 0x788a8fd6ea20> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df_group = df.groupby('pekerjaan').agg({
/tmp/ipykernel_506/4252965023.py:1: FutureWarning: The provided callable <function std at 0x788a8fd6ff60> is currently using SeriesGroupBy.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  df_group = df.groupby('pekerjaan').agg({
/tmp/ipykernel_506/4252965023.py:1: Futu

usia                  gaji                   
               mean sum       std    mean   sum          std
pekerjaan                                                   
DB Admin       23.0  23       NaN  3000.0  3000          NaN
Programer      28.5  57  7.778175  3500.0  7000  2121.320344
Web Developer  20.0  20       NaN  2400.0  2400          NaN

In [ ]:
kiri = pd.DataFrame({
    'Id': [2, 3, 1],
    'Nama': ['Andi', 'Joko', 'Budi']
})
kanan = pd.DataFrame({
    'Id': [1, 2, 3],
    'Nama': ['Mike', 'Jack', 'Jane']
})

gabung= pd.merge(kiri, kanan, on='Id', sort=True)
gabung

,Id,Nama_x,Nama_y
0,1,Budi,Mike
1,2,Andi,Jack
2,3,Joko,Jane


In [ ]:
karyawan = pd.DataFrame({
    'Nama': ['Andi', 'Joko', 'Budi', 'Mike', 'Jack', 'Jane'],
    'Alamat': ['Jakarta', 'Bandung', 'Surabaya', 'Jakarta', 'Bandung', 'Surabaya'],
    'Id Pekerjaan': [1, 2, 3, 1, 2, 4]
})
pekerjaan = pd.DataFrame({
    'Id Pekerjaan': [1, 2, 3],
    'Nama': ['Programer', 'DB Admin', 'Web Developer'],
    'Gaji': [2000, 3000, 2400]
})

print(karyawan)
print(pekerjaan)

   Nama    Alamat  Id Pekerjaan
0  Andi   Jakarta             1
1  Joko   Bandung             2
2  Budi  Surabaya             3
3  Mike   Jakarta             1
4  Jack   Bandung             2
5  Jane  Surabaya             4
   Id Pekerjaan           Nama  Gaji
0             1      Programer  2000
1             2       DB Admin  3000
2             3  Web Developer  2400


In [ ]:
gabung_merge = pd.merge(karyawan, pekerjaan, on='Id Pekerjaan', how='left', sort=True)
gabung_merge

,Nama_x,Alamat,Id Pekerjaan,Nama_y,Gaji
0,Andi,Jakarta,1,Programer,2000.0
1,Mike,Jakarta,1,Programer,2000.0
2,Joko,Bandung,2,DB Admin,3000.0
3,Jack,Bandung,2,DB Admin,3000.0
4,Budi,Surabaya,3,Web Developer,2400.0
5,Jane,Surabaya,4,NaN,NaN


In [ ]:
gabung_merge = pd.merge(karyawan, pekerjaan, on='Id Pekerjaan', how='right', sort=True, suffixes=('_pegawai', '_pekerjaan'))
gabung_merge

,Nama_pegawai,Alamat,Id Pekerjaan,Nama_pekerjaan,Gaji
0,Andi,Jakarta,1,Programer,2000
1,Mike,Jakarta,1,Programer,2000
2,Joko,Bandung,2,DB Admin,3000
3,Jack,Bandung,2,DB Admin,3000
4,Budi,Surabaya,3,Web Developer,2400


In [ ]:
gabung_join = karyawan.join(pekerjaan, how='left', rsuffix='_pekerjaan')
gabung_join

,Nama,Alamat,Id Pekerjaan,Id Pekerjaan_pekerjaan,Nama_pekerjaan,Gaji
0,Andi,Jakarta,1,1.0,Programer,2000.0
1,Joko,Bandung,2,2.0,DB Admin,3000.0
2,Budi,Surabaya,3,3.0,Web Developer,2400.0
3,Mike,Jakarta,1,NaN,NaN,NaN
4,Jack,Bandung,2,NaN,NaN,NaN
5,Jane,Surabaya,4,NaN,NaN,NaN


In [ ]:
kiri = pd.DataFrame({
    'Nama' : ['Budi', 'Joko', 'Maya'],
    'Alamat' : ['Jakarta', 'Bandung', 'Surabaya'],
})
kanan = pd.DataFrame({
    'Nama' : ['Jane', 'Mike', ' Dave'],
    'Alamat' : ['Semarang', 'Yogyakarta', 'Solo'],
})

gabung_concat = pd.concat([kiri, kanan], axis=0, ignore_index=True)
gabung_concat

,Nama,Alamat
0,Budi,Jakarta
1,Joko,Bandung
2,Maya,Surabaya
3,Jane,Semarang
4,Mike,Yogyakarta
5,Dave,Solo


In [ ]:
kiri = pd.DataFrame({
    'Nama' : ['Budi', 'Joko', 'Maya'],
    'Alamat' : ['Jakarta', 'Bandung', 'Surabaya'],
})
kanan = pd.DataFrame({
    'Nama' : ['Jane', 'Mike', ' Dave'],
    'Gaji' : [2000, 3000, 2400],
})
gabung_concat = pd.concat([kiri, kanan], axis=0, ignore_index=True, join='outer')
gabung_concat

,Nama,Alamat,Gaji
0,Budi,Jakarta,NaN
1,Joko,Bandung,NaN
2,Maya,Surabaya,NaN
3,Jane,NaN,2000.0
4,Mike,NaN,3000.0
5,Dave,NaN,2400.0


In [ ]:
kiri = pd.DataFrame({
    'Nama' : ['Budi', 'Joko', 'Maya'],
    'Alamat' : ['Jakarta', 'Bandung', 'Surabaya'],
})
kanan = pd.DataFrame({
    'Pekerjaan' : ['Programer', 'Data Engineer', 'Manager', 'Web Developer'],
    'Gaji' : [2000, 3000, 2400, 5000],
})
gabung_concat = pd.concat([kiri, kanan], axis=1, join='outer')
gabung_concat

,Nama,Alamat,Pekerjaan,Gaji
0,Budi,Jakarta,Programer,2000
1,Joko,Bandung,Data Engineer,3000
2,Maya,Surabaya,Manager,2400
3,NaN,NaN,Web Developer,5000


In [ ]:
kiri = pd.DataFrame({
    'Nama' : ['Budi', 'Joko', 'Maya'],
    'Alamat' : ['Jakarta', 'Bandung', 'Surabaya'],
})
kanan = pd.DataFrame({
    'Nama' : ['Jane', 'Mike', ' Dave'],
    'Alamat' : ['Semarang', 'Yogyakarta', 'Solo'],
})

gabung_append = pd.concat([kiri, kanan], ignore_index=True)
gabung_append

,Nama,Alamat
0,Budi,Jakarta
1,Joko,Bandung
2,Maya,Surabaya
3,Jane,Semarang
4,Mike,Yogyakarta
5,Dave,Solo


In [ ]:
new = gabung_append.reset_index(drop=True)
new

,Nama,Alamat
0,Budi,Jakarta
1,Joko,Bandung
2,Maya,Surabaya
3,Jane,Semarang
4,Mike,Yogyakarta
5,Dave,Solo


In [ ]:
kiri = pd.DataFrame({
    'ID' : ['001', '002', '003'],
    'Nama' : ['Budi', 'Joko', 'Maya'],
    'Alamat' : ['Jakarta', 'Bandung', 'Surabaya'],
})
kiri

,ID,Nama,Alamat
0,001,Budi,Jakarta
1,002,Joko,Bandung
2,003,Maya,Surabaya


In [ ]:
kiri.iloc[2]

,2
ID,003
Nama,Maya
Alamat,Surabaya


In [ ]:
kiri.set_index('ID', inplace=True)
kiri

,Nama,Alamat
ID,,
001,Budi,Jakarta
002,Joko,Bandung
003,Maya,Surabaya


In [ ]:
kiri.loc['003']

,003
Nama,Maya
Alamat,Surabaya


In [ ]:
karyawan = pd.DataFrame({
    'Emp_id' : ['001', '002', '003', '004', '005', '006'],
    'Nama' : ['Budi', 'Joko', 'Maya', 'Andi', 'Dewi', 'Dian'],
    'Gender' : ['Pria', 'Pria', 'Wanita', 'Pria', 'Wanita', 'Wanita'],
    'Pekerjaan' : ['Programer', 'Data Engineer', 'Manager', 'Web Developer', 'Programer', 'Web Developer'],
    'Gaji' : [2000, 3000, 2400, 6000, 8000, 6000]
})
karyawan

,Emp_id,Nama,Gender,Pekerjaan,Gaji
0,001,Budi,Pria,Programer,2000
1,002,Joko,Pria,Data Engineer,3000
2,003,Maya,Wanita,Manager,2400
3,004,Andi,Pria,Web Developer,6000
4,005,Dewi,Wanita,Programer,8000
5,006,Dian,Wanita,Web Developer,6000


In [ ]:
pivot_table = pd.pivot_table(karyawan, columns=['Gender', 'Pekerjaan'], aggfunc={'Gaji' : 'sum', 'Pekerjaan': 'count'})
pivot_table

Gender             Pria                          Wanita            \
Pekerjaan Data Engineer Programer Web Developer Manager Programer   
Gaji               3000      2000          6000    2400      8000   
Pekerjaan             1         1             1       1         1   

Gender                   
Pekerjaan Web Developer  
Gaji               6000  
Pekerjaan             1

In [ ]:
import numpy as np

pivot_table = pd.pivot_table(karyawan, columns=['Gender', 'Pekerjaan'], aggfunc={'Gaji' : np.sum, 'Pekerjaan': 'count'})
pivot_table

/tmp/ipykernel_506/2067426380.py:3: FutureWarning: The provided callable <function sum at 0x788a8fd6ea20> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pivot_table = pd.pivot_table(karyawan, columns=['Gender', 'Pekerjaan'], aggfunc={'Gaji' : np.sum, 'Pekerjaan': 'count'})


Gender             Pria                          Wanita            \
Pekerjaan Data Engineer Programer Web Developer Manager Programer   
Gaji               3000      2000          6000    2400      8000   
Pekerjaan             1         1             1       1         1   

Gender                   
Pekerjaan Web Developer  
Gaji               6000  
Pekerjaan             1

In [ ]:
mahasiswa = pd.DataFrame({
    'Mhs_id' : ['001', '002', '003'],
    'Nama' : ['Budi', 'Joko', 'Maya'],
    'Bhs Inggris' : [100, 90, 98],
    'Matematika' : [90, 87, 72],
    'Ekonomi' : [90, 80, 78]
})
mahasiswa

,Mhs_id,Nama,Bhs Inggris,Matematika,Ekonomi
0,001,Budi,100,90,90
1,002,Joko,90,87,80
2,003,Maya,98,72,78


In [ ]:
melt_table = pd.melt(mahasiswa, id_vars=['Mhs_id', 'Nama'], value_vars=['Bhs Inggris', 'Matematika', 'Ekonomi'])
melt_table

,Mhs_id,Nama,variable,value
0,001,Budi,Bhs Inggris,100
1,002,Joko,Bhs Inggris,90
2,003,Maya,Bhs Inggris,98
3,001,Budi,Matematika,90
4,002,Joko,Matematika,87
5,003,Maya,Matematika,72
6,001,Budi,Ekonomi,90
7,002,Joko,Ekonomi,80
8,003,Maya,Ekonomi,78


In [ ]:
x = lambda var1, var2 : var1 + var2
hasil = x(10, 12)
hasil

22

In [ ]:
test = lambda var1 : var1 * 2
hasil = test(5)

hasil

10

In [ ]:
mahasiswa = pd.DataFrame({
    'Mhs_id' : ['001', '002', '003'],
    'Nama' : ['Budi', 'Joko', 'Maya'],
    'Matematika' : [90, 47, 72]
})
mahasiswa

,Mhs_id,Nama,Matematika
0,001,Budi,90
1,002,Joko,47
2,003,Maya,72


In [ ]:
mahasiswa['Grade'] = mahasiswa['Matematika'].apply(lambda nilai : 'A' if nilai >=90 else('B' if nilai>=70 and nilai<90 else ('C')))
mahasiswa

,Mhs_id,Nama,Matematika,Grade
0,001,Budi,90,A
1,002,Joko,47,C
2,003,Maya,72,B


In [ ]:
from google.colab import drive

drive.mount('/content/gdrive/')

Mounted at /content/gdrive/


In [ ]:
df = pd.read_csv('/content/gdrive/MyDrive/Activity/Kuliah/datatraining.txt')
df

,date,Temperature,Humidity,Light,CO2,HumidityRatio,Occupancy
1,2015-02-04 17:51:00,23.18,27.2720,426.0,721.250000,0.004793,1
2,2015-02-04 17:51:59,23.15,27.2675,429.5,714.000000,0.004783,1
3,2015-02-04 17:53:00,23.15,27.2450,426.0,713.500000,0.004779,1
4,2015-02-04 17:54:00,23.15,27.2000,426.0,708.250000,0.004772,1
5,2015-02-04 17:55:00,23.10,27.2000,426.0,704.500000,0.004757,1
...,...,...,...,...,...,...,...
8139,2015-02-10 09:29:00,21.05,36.0975,433.0,787.250000,0.005579,1
8140,2015-02-10 09:29:59,21.05,35.9950,433.0,789.500000,0.005563,1
8141,2015-02-10 09:30:59,21.10,36.0950,433.0,798.500000,0.005596,1
8142,2015-02-10 09:32:00,21.10,36.2600,433.0,820.333333,0.005621,1


Tugas dan Analisis

In [ ]:
import numpy as np

random_array_4x4 = np.random.randint(0, 51, size=(4, 4))
print("Array 4x4:\n", random_array_4x4)
reshaped_array_2x8 = random_array_4x4.reshape(2, 8)
print("\nArray 2x8:\n", reshaped_array_2x8)
filtered_elements = reshaped_array_2x8[reshaped_array_2x8 > 25]
print("\nElemen yang bernilai lebih dari 25:\n", filtered_elements)

Array 4x4:
 [[11 50 39 39]
 [41  0 25 16]
 [50 16 48 13]
 [28 42 43 16]]

Array 2x8:
 [[11 50 39 39 41  0 25 16]
 [50 16 48 13 28 42 43 16]]

Elemen yang bernilai lebih dari 25:
 [50 39 39 41 50 48 28 42 43]


In [ ]:
import pandas as pd
import numpy as np

df_karyawan = pd.DataFrame({
    'Nama': ['Budi', 'Joko', 'Maya', 'Andi', 'Dewi', 'Dian'],
    'Pekerjaan': ['Programer', 'Data Engineer', 'Manager', 'Web Developer', 'Programer', 'Web Developer'],
    'Gaji': [2000, 3000, 2400, 6000, 8000, 6000]
})

print("DataFrame Karyawan:\n", df_karyawan)
agg_gaji_by_pekerjaan = df_karyawan.groupby('Pekerjaan').agg(
    Gaji_Max=('Gaji', 'max'),
    Gaji_Min=('Gaji', 'min'),
    Gaji_Std=('Gaji', 'std')
)

print("\nAgregasi Gaji per Pekerjaan:\n", agg_gaji_by_pekerjaan)

DataFrame Karyawan:
    Nama      Pekerjaan  Gaji
0  Budi      Programer  2000
1  Joko  Data Engineer  3000
2  Maya        Manager  2400
3  Andi  Web Developer  6000
4  Dewi      Programer  8000
5  Dian  Web Developer  6000

Agregasi Gaji per Pekerjaan:
                Gaji_Max  Gaji_Min     Gaji_Std
Pekerjaan                                     
Data Engineer      3000      3000          NaN
Manager            2400      2400          NaN
Programer          8000      2000  4242.640687
Web Developer      6000      6000     0.000000


In [ ]:
import pandas as pd

df_karyawan = pd.DataFrame({
    'Emp_id': ['E001', 'E002', 'E003', 'E004'],
    'Nama': ['Andi', 'Budi', 'Cici', 'Dedi'],
    'Divisi': ['HR', 'IT', 'Marketing', 'IT']
})
print("DataFrame Karyawan:\n", df_karyawan)
df_gaji = pd.DataFrame({
    'ID': ['E001', 'E002', 'E003', 'E005'],
    'Gaji': [50000, 60000, 55000, 70000],
    'Status': ['Aktif', 'Aktif', 'Aktif', 'Tidak Aktif']
})
print("\nDataFrame Gaji:\n", df_gaji)
merged_df = pd.merge(
    df_karyawan,
    df_gaji,
    left_on='Emp_id',
    right_on='ID',
    how='left',
    suffixes=('_karyawan', '_gaji')
)

print("\nDataFrame setelah digabung (Left Join):\n", merged_df)

DataFrame Karyawan:
   Emp_id  Nama     Divisi
0   E001  Andi         HR
1   E002  Budi         IT
2   E003  Cici  Marketing
3   E004  Dedi         IT

DataFrame Gaji:
      ID   Gaji       Status
0  E001  50000        Aktif
1  E002  60000        Aktif
2  E003  55000        Aktif
3  E005  70000  Tidak Aktif

DataFrame setelah digabung (Left Join):
   Emp_id  Nama     Divisi    ID     Gaji Status
0   E001  Andi         HR  E001  50000.0  Aktif
1   E002  Budi         IT  E002  60000.0  Aktif
2   E003  Cici  Marketing  E003  55000.0  Aktif
3   E004  Dedi         IT   NaN      NaN    NaN
